version: '3.5'
services:
  postgres:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
